name: {{cookiecutter.project_slug}}
channels:
  - conda-forge
  - defaults
dependencies:
# C++ project dependencies
  - catch2=2.6
  - pybind11=2.2
  - swig=3.0
  - eigen=3.3
# Python project dependencies

